"""
This type stub file was generated by pyright.
"""

from types import EllipsisType
from scipy._lib._array_api import Array, ArrayLike

def from_matrix(matrix: Array, normalize: bool = ..., copy: bool = ...) -> Array:
    ...

def from_rotation(quat: Array) -> Array:
    ...

def from_translation(translation: Array) -> Array:
    ...

def from_components(translation: Array, quat: Array) -> Array:
    ...

def from_exp_coords(exp_coords: Array) -> Array:
    ...

def from_dual_quat(dual_quat: Array, *, scalar_first: bool = ...) -> Array:
    ...

def as_exp_coords(matrix: Array) -> Array:
    ...

def as_dual_quat(matrix: Array, *, scalar_first: bool = ...) -> Array:
    ...

def compose_transforms(tf_matrix: Array, other_tf_matrix: Array) -> Array:
    ...

def inv(matrix: Array) -> Array:
    ...

def apply(matrix: Array, vector: Array, inverse: bool = ...) -> Array:
    ...

def pow(matrix: Array, n: float | Array) -> Array:
    ...

def mean(matrix: Array, weights: ArrayLike | None = ..., axis: None | int | tuple[int, ...] = ...) -> Array:
    ...

def setitem(matrix: Array, indexer: Array | int | tuple | slice | EllipsisType | None, value: Array) -> Array:
    ...

def normalize_dual_quaternion(dual_quat: Array) -> Array:
    """Normalize dual quaternion."""
    ...

