"""
This type stub file was generated by pyright.
"""

from types import EllipsisType
from scipy._lib._array_api import Array, ArrayLike

"""Array API backend for the `Rotation` class.

This module provides generic, functional implementations of the `Rotation` class methods
that work with any Array API-compatible backend.
"""
def from_quat(quat: Array, normalize: bool = ..., copy: bool = ..., *, scalar_first: bool = ...) -> Array:
    ...

def from_matrix(matrix: Array, assume_valid: bool = ...) -> Array:
    ...

def from_rotvec(rotvec: Array, degrees: bool = ...) -> Array:
    ...

def from_mrp(mrp: Array) -> Array:
    ...

def from_euler(seq: str, angles: Array, degrees: bool = ...) -> Array:
    ...

def from_davenport(axes: Array, order: str, angles: Array | float, degrees: bool = ...) -> Array:
    ...

def as_quat(quat: Array, canonical: bool = ..., *, scalar_first: bool = ...) -> Array:
    ...

def as_matrix(quat: Array) -> Array:
    ...

def as_rotvec(quat: Array, degrees: bool = ...) -> Array:
    ...

def as_mrp(quat: Array) -> Array:
    ...

def as_euler(quat: Array, seq: str, degrees: bool = ..., *, suppress_warnings: bool = ...) -> Array:
    ...

def as_davenport(quat: Array, axes: ArrayLike, order: str, degrees: bool = ..., *, suppress_warnings: bool = ...) -> Array:
    ...

def inv(quat: Array) -> Array:
    ...

def magnitude(quat: Array) -> Array:
    ...

def approx_equal(quat: Array, other: Array, atol: float | None = ..., degrees: bool = ...) -> Array:
    ...

def mean(quat: Array, weights: ArrayLike | None = ..., axis: None | int | tuple[int, ...] = ...) -> Array:
    ...

def reduce(quat: Array, left: Array | None = ..., right: Array | None = ...) -> tuple[Array, Array | None, Array | None]:
    ...

def apply(quat: Array, points: Array, inverse: bool = ...) -> Array:
    ...

def setitem(quat: Array, value: Array, indexer: int | slice | EllipsisType | None) -> Array:
    ...

def align_vectors(a: Array, b: Array, weights: Array | None = ..., return_sensitivity: bool = ...) -> tuple[Array, Array, Array]:
    ...

def pow(quat: Array, n: float | Array) -> Array:
    ...

def compose_quat(p: Array, q: Array) -> Array:
    ...

