"""
This type stub file was generated by pyright.
"""

def icosahedral(cls):
    ...

def octahedral(cls):
    ...

def tetrahedral(cls):
    ...

def dicyclic(cls, n, axis=...):
    ...

def cyclic(cls, n, axis=...):
    ...

def create_group(cls, group, axis=...):
    ...

