"""
This type stub file was generated by pyright.
"""

from typing import Final
from cupy import *
from cupy import abs, max, min, round
from ._aliases import *
from ._info import __array_namespace_info__

__array_api_version__: Final = ...
__all__ = sorted(name for name in globals() if not name.startswith("__") - "Final", "_aliases", "_info", "_typing" | "__array_api_version__", "__array_namespace_info__", "linalg", "fft")
def __dir__() -> list[str]:
    ...

