"""
This type stub file was generated by pyright.
"""

__all__ = ['_svdp']
_lansvd_dict = ...
_lansvd_irl_dict = ...
_which_converter = ...
class _AProd:
    """
    Wrapper class for linear operator

    The call signature of the __call__ method matches the callback of
    the PROPACK routines.
    """
    def __init__(self, A) -> None:
        ...
    
    def __call__(self, transa, m, n, x, y): # -> None:
        ...
    
    @property
    def shape(self): # -> tuple[Any, ...]:
        ...
    
    @property
    def dtype(self): # -> dtype[Any] | dtype[int_ | numpy.bool[builtins.bool]]:
        ...
    


