"""
This type stub file was generated by pyright.
"""

__all__ = ['CloughTocher2DInterpolator', 'LinearNDInterpolator']
def __dir__(): # -> list[str]:
    ...

def __getattr__(name): # -> Any | None:
    ...

