"""
This type stub file was generated by pyright.
"""

from collections.abc import Callable, Sequence
from types import ModuleType
from typing import Literal, overload
from ._utils._typing import Array, DType, Device

"""Array-agnostic implementations for the public API."""
__all__ = ["apply_where", "atleast_nd", "broadcast_shapes", "cov", "create_diagonal", "expand_dims", "kron", "nunique", "pad", "setdiff1d", "sinc"]
@overload
def apply_where(cond: Array, args: Array | tuple[Array, ...], f1: Callable[..., Array], f2: Callable[..., Array], /, *, xp: ModuleType | None = ...) -> Array:
    ...

@overload
def apply_where(cond: Array, args: Array | tuple[Array, ...], f1: Callable[..., Array], /, *, fill_value: Array | complex, xp: ModuleType | None = ...) -> Array:
    ...

def apply_where(cond: Array, args: Array | tuple[Array, ...], f1: Callable[..., Array], f2: Callable[..., Array] | None = ..., /, *, fill_value: Array | complex | None = ..., xp: ModuleType | None = ...) -> Array:
    """
    Run one of two elementwise functions depending on a condition.

    Equivalent to ``f1(*args) if cond else fill_value`` performed elementwise
    when `fill_value` is defined, otherwise to ``f1(*args) if cond else f2(*args)``.

    Parameters
    ----------
    cond : array
        The condition, expressed as a boolean array.
    args : Array or tuple of Arrays
        Argument(s) to `f1` (and `f2`). Must be broadcastable with `cond`.
    f1 : callable
        Elementwise function of `args`, returning a single array.
        Where `cond` is True, output will be ``f1(arg0[cond], arg1[cond], ...)``.
    f2 : callable, optional
        Elementwise function of `args`, returning a single array.
        Where `cond` is False, output will be ``f2(arg0[cond], arg1[cond], ...)``.
        Mutually exclusive with `fill_value`.
    fill_value : Array or scalar, optional
        If provided, value with which to fill output array where `cond` is False.
        It does not need to be scalar; it needs however to be broadcastable with
        `cond` and `args`.
        Mutually exclusive with `f2`. You must provide one or the other.
    xp : array_namespace, optional
        The standard-compatible namespace for `cond` and `args`. Default: infer.

    Returns
    -------
    Array
        An array with elements from the output of `f1` where `cond` is True and either
        the output of `f2` or `fill_value` where `cond` is False. The returned array has
        data type determined by type promotion rules between the output of `f1` and
        either `fill_value` or the output of `f2`.

    Notes
    -----
    ``xp.where(cond, f1(*args), f2(*args))`` requires explicitly evaluating `f1` even
    when `cond` is False, and `f2` when cond is True. This function evaluates each
    function only for their matching condition, if the backend allows for it.

    On Dask, `f1` and `f2` are applied to the individual chunks and should use functions
    from the namespace of the chunks.

    Examples
    --------
    >>> import array_api_strict as xp
    >>> import array_api_extra as xpx
    >>> a = xp.asarray([5, 4, 3])
    >>> b = xp.asarray([0, 2, 2])
    >>> def f(a, b):
    ...     return a // b
    >>> xpx.apply_where(b != 0, (a, b), f, fill_value=xp.nan)
    array([ nan,  2., 1.])
    """
    ...

def atleast_nd(x: Array, /, *, ndim: int, xp: ModuleType) -> Array:
    """See docstring in array_api_extra._delegation."""
    ...

def broadcast_shapes(*shapes: tuple[float | None, ...]) -> tuple[int | None, ...]:
    """
    Compute the shape of the broadcasted arrays.

    Duplicates :func:`numpy.broadcast_shapes`, with additional support for
    None and NaN sizes.

    This is equivalent to ``xp.broadcast_arrays(arr1, arr2, ...)[0].shape``
    without needing to worry about the backend potentially deep copying
    the arrays.

    Parameters
    ----------
    *shapes : tuple[int | None, ...]
        Shapes of the arrays to broadcast.

    Returns
    -------
    tuple[int | None, ...]
        The shape of the broadcasted arrays.

    See Also
    --------
    numpy.broadcast_shapes : Equivalent NumPy function.
    array_api.broadcast_arrays : Function to broadcast actual arrays.

    Notes
    -----
    This function accepts the Array API's ``None`` for unknown sizes,
    as well as Dask's non-standard ``math.nan``.
    Regardless of input, the output always contains ``None`` for unknown sizes.

    Examples
    --------
    >>> import array_api_extra as xpx
    >>> xpx.broadcast_shapes((2, 3), (2, 1))
    (2, 3)
    >>> xpx.broadcast_shapes((4, 2, 3), (2, 1), (1, 3))
    (4, 2, 3)
    """
    ...

def cov(m: Array, /, *, xp: ModuleType) -> Array:
    """See docstring in array_api_extra._delegation."""
    ...

def one_hot(x: Array, /, num_classes: int, *, xp: ModuleType) -> Array:
    """See docstring in `array_api_extra._delegation.py`."""
    ...

def create_diagonal(x: Array, /, *, offset: int = ..., xp: ModuleType) -> Array:
    """See docstring in array_api_extra._delegation."""
    ...

def default_dtype(xp: ModuleType, kind: Literal["real floating", "complex floating", "integral", "indexing"] = ..., *, device: Device | None = ...) -> DType:
    """
    Return the default dtype for the given namespace and device.

    This is a convenience shorthand for
    ``xp.__array_namespace_info__().default_dtypes(device=device)[kind]``.

    Parameters
    ----------
    xp : array_namespace
        The standard-compatible namespace for which to get the default dtype.
    kind : {'real floating', 'complex floating', 'integral', 'indexing'}, optional
        The kind of dtype to return. Default is 'real floating'.
    device : Device, optional
        The device for which to get the default dtype. Default: current device.

    Returns
    -------
    dtype
        The default dtype for the given namespace, kind, and device.
    """
    ...

def expand_dims(a: Array, /, *, axis: tuple[int, ...] = ..., xp: ModuleType) -> Array:
    """See docstring in array_api_extra._delegation."""
    ...

def isclose(a: Array | complex, b: Array | complex, *, rtol: float = ..., atol: float = ..., equal_nan: bool = ..., xp: ModuleType) -> Array:
    """See docstring in array_api_extra._delegation."""
    ...

def kron(a: Array | complex, b: Array | complex, /, *, xp: ModuleType | None = ...) -> Array:
    """
    Kronecker product of two arrays.

    Computes the Kronecker product, a composite array made of blocks of the
    second array scaled by the first.

    Equivalent to ``numpy.kron`` for NumPy arrays.

    Parameters
    ----------
    a, b : Array | int | float | complex
        Input arrays or scalars. At least one must be an array.
    xp : array_namespace, optional
        The standard-compatible namespace for `a` and `b`. Default: infer.

    Returns
    -------
    array
        The Kronecker product of `a` and `b`.

    Notes
    -----
    The function assumes that the number of dimensions of `a` and `b`
    are the same, if necessary prepending the smallest with ones.
    If ``a.shape = (r0,r1,..,rN)`` and ``b.shape = (s0,s1,...,sN)``,
    the Kronecker product has shape ``(r0*s0, r1*s1, ..., rN*SN)``.
    The elements are products of elements from `a` and `b`, organized
    explicitly by::

        kron(a,b)[k0,k1,...,kN] = a[i0,i1,...,iN] * b[j0,j1,...,jN]

    where::

        kt = it * st + jt,  t = 0,...,N

    In the common 2-D case (N=1), the block structure can be visualized::

        [[ a[0,0]*b,   a[0,1]*b,  ... , a[0,-1]*b  ],
         [  ...                              ...   ],
         [ a[-1,0]*b,  a[-1,1]*b, ... , a[-1,-1]*b ]]

    Examples
    --------
    >>> import array_api_strict as xp
    >>> import array_api_extra as xpx
    >>> xpx.kron(xp.asarray([1, 10, 100]), xp.asarray([5, 6, 7]), xp=xp)
    Array([  5,   6,   7,  50,  60,  70, 500,
           600, 700], dtype=array_api_strict.int64)

    >>> xpx.kron(xp.asarray([5, 6, 7]), xp.asarray([1, 10, 100]), xp=xp)
    Array([  5,  50, 500,   6,  60, 600,   7,
            70, 700], dtype=array_api_strict.int64)

    >>> xpx.kron(xp.eye(2), xp.ones((2, 2)), xp=xp)
    Array([[1., 1., 0., 0.],
           [1., 1., 0., 0.],
           [0., 0., 1., 1.],
           [0., 0., 1., 1.]], dtype=array_api_strict.float64)

    >>> a = xp.reshape(xp.arange(100), (2, 5, 2, 5))
    >>> b = xp.reshape(xp.arange(24), (2, 3, 4))
    >>> c = xpx.kron(a, b, xp=xp)
    >>> c.shape
    (2, 10, 6, 20)
    >>> I = (1, 3, 0, 2)
    >>> J = (0, 2, 1)
    >>> J1 = (0,) + J             # extend to ndim=4
    >>> S1 = (1,) + b.shape
    >>> K = tuple(xp.asarray(I) * xp.asarray(S1) + xp.asarray(J1))
    >>> c[K] == a[I]*b[J]
    Array(True, dtype=array_api_strict.bool)
    """
    ...

def nan_to_num(x: Array, /, fill_value: int | float = ..., *, xp: ModuleType) -> Array:
    """See docstring in `array_api_extra._delegation.py`."""
    ...

def nunique(x: Array, /, *, xp: ModuleType | None = ...) -> Array:
    """
    Count the number of unique elements in an array.

    Compatible with JAX and Dask, whose laziness would be otherwise
    problematic.

    Parameters
    ----------
    x : Array
        Input array.
    xp : array_namespace, optional
        The standard-compatible namespace for `x`. Default: infer.

    Returns
    -------
    array: 0-dimensional integer array
        The number of unique elements in `x`. It can be lazy.
    """
    ...

def pad(x: Array, pad_width: int | tuple[int, int] | Sequence[tuple[int, int]], *, constant_values: complex = ..., xp: ModuleType) -> Array:
    """See docstring in `array_api_extra._delegation.py`."""
    ...

def setdiff1d(x1: Array | complex, x2: Array | complex, /, *, assume_unique: bool = ..., xp: ModuleType) -> Array:
    """See docstring in `array_api_extra._delegation.py`."""
    ...

def sinc(x: Array, /, *, xp: ModuleType) -> Array:
    """See docstring in `array_api_extra._delegation.py`."""
    ...

def partition(x: Array, kth: int, /, axis: int = ..., *, xp: ModuleType) -> Array:
    """See docstring in `array_api_extra._delegation.py`."""
    ...

def argpartition(x: Array, kth: int, /, axis: int = ..., *, xp: ModuleType) -> Array:
    """See docstring in `array_api_extra._delegation.py`."""
    ...

def isin(a: Array, b: Array, /, *, assume_unique: bool = ..., invert: bool = ..., xp: ModuleType) -> Array:
    """See docstring in `array_api_extra._delegation.py`."""
    ...

