"""
This type stub file was generated by pyright.
"""

from typing import Final
from .._internal import clone_module
from . import _aliases
from ._aliases import *
from ._info import __array_namespace_info__

__all__ = clone_module("torch", globals())
__array_api_version__: Final = ...
__all__ = sorted(set(__all__) | set(_aliases.__all__) | "__array_api_version__", "__array_namespace_info__", "linalg", "fft")
def __dir__() -> list[str]:
    ...

